version: "3.8"

services:
  cloudflared-keycloak:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-keycloak
    command: tunnel --no-autoupdate --url http://keycloak:8080
    networks:
      - app-net

networks:
  app-net:
    external: true