package com.evatech.bidplatform.bid.entity;


public enum BidStatus {

    ASSIGNED,
    DOCUMENT_GENERATED,
    DRAFT,
    UPLOADED,
    AI_FILL_IN_PROGRESS,
    AI_FORM_FILLED,
    AI_FILL_FAILED,
    USER_REVIEW_PENDING,
    USER_REVIEWED,
    USER_REFILL_REQUESTED,
    SUBMITTED_FOR_APPROVAL,
    APPROVED,
    REJECTED
}