package com.evatech.bidplatform.bid.entity;

import com.evatech.bidplatform.contract.entity.ContractDocumentFieldValue;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import lombok.Getter;
import lombok.Setter;
import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "bid_template_field")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BidTemplateField {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Internal placeholder used in DOCX
     * Example: {{FIELD_101}}
     */
    @Column(name = "placeholder", nullable = false, unique = true)
    private String placeholder;

    /**
     * Field label shown in template
     * Example: "Price Per Bed"
     */
    @Column(name = "field_label", nullable = false)
    private String fieldLabel;

    /**
     * NUMBER, TEXT, DATE, BOOLEAN...
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "field_type", nullable = false)
    private BidTemplateFieldType fieldType;

    /**
     * Required field?
     */
    @Column(name = "required", nullable = false)
    private boolean required;

    /**
     * Default value generated by AI
     */
    @Column(name = "default_value")
    private String defaultValue;

    /**
     * Template document that contains this field
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "generated_document_id", nullable = false)
    private GeneratedDocument generatedDocument;

    @OneToOne(
            mappedBy = "templateField",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private ContractDocumentFieldValue fieldValue;

}