server:
  port: 8083

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://mysql-local:3306/bidding?createDatabaseIfNotExist=true
    username: root
    password: root
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      validation-timeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/master
  mail:
    host: smtp.gmail.com
    port: 587
    username: ankitmanchanda07@gmail.com
    password: TEST
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always



ai:
  type: github_model
  api:
    key: ${GITHUB_TOKEN}

project:
  base-dir: generated-projects

file:
  storage:
    base-path: ${FILE_STORAGE_BASE_PATH:/app/storage}

parameter:
  max-char-per-request: 35000
  min-delay-ms: 3000
  batch-size: 5
  max-retry: 5
  wait-time: 20000
  max-repair-retry: 20
  chunk_size: 8000
  chunk_overlap: 1000

# KEYCLOAK
keycloak:
  url: ${keycloak.url}
  realm: master
  clientid: evatech
  username: admin
  password: admin
  clientsecret: iX1xrfeAO6VkdkwmKPNqdxsP7JUrrfEm

self:
  service:
    url: http://localhost:8083/

app:
  mock-ai-enabled: true